name: Android CI

on: [push, pull_request]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Build GRaceController
        run: |
          cd android/GRaceController
          ./gradlew build --stacktrace
