name: Android CI

on: [push, pull_request]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Change Gradle Permission
        run: |
          cd android/GRace
          chmod +x gradlew
      - name: Build GRace
        run: |
          cd android/GRace
  
          ./gradlew build --stacktrace

  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Run unit tests for GRace
        run: |
          cd android/GRace
  
          ./gradlew test --info

 