name: Android CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Build with Gradle
      run: |
          cd Android/islandRush
          ./gradlew build

  run-instrumented-tests:
    runs-on: macos-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: make gradlew available
        run: |
            cd android/islandRush
            chmod +x gradlew
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Run instrumented tests for IslandRush
        uses: reactivecircus/android-emulator-runner@v2
        with:
          profile: Nexus 6
          api-level: 29
          arch: x86_64
          working-directory: ./Android/islandRush
          script: ./gradlew connectedCheck

