name: GameServer CI

on: [push, pull_request]

jobs:
  build-program:

    runs-on: ubuntu-20.04

    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Install JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
      - name: Build Program
        run: |
          javac compile GameServer/*.java