name: GameServer CI

on: [push, pull_request]

jobs:
  build-program:

    runs-on: ubuntu-20.04

    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build Program
        run: |
          javac GameServer/src/main/java/main.java