name: GameServer CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Clone Repo
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        cd GameServer/src/main/java/main.java
        mvn compile
