name: Build Island.zip Artifact

on: [push, pull_request, workflow_dispatch] 
       
env: 
  GODOT_VERSION: 3.4.4 
  EXPORT_NAME: Mod # directory where the Godot project is

jobs:
  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:mono-latest # not sure this image works with godot 3.4.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Resolve Dependencies
        run: |
          mkdir -v -p build/mods
          cd $EXPORT_NAME
          timeout 30s godot . --editor --no-window 
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with: # the final result should be called Island.zip
          name: Island
          path: build/mods
